### ISSUE TITLE
Dataset picture gallery scrollbar is hidden by title bar

### ISSUE THREAD

**Issue by NLZ432** [wpilibsuite/Axon#151] opened 2021-01-23 01:05 UTC
apparent with very large datasets

![image](https://user-images.githubusercontent.com/65617676/105563713-24d6e600-5ced-11eb-9ac4-12dfcae75851.jpeg)

![image](https://user-images.githubusercontent.com/65617676/105563720-2a343080-5ced-11eb-8778-d8048948d43d.jpeg)

![image](https://user-images.githubusercontent.com/65617676/105563726-30c2a800-5ced-11eb-853d-b233856b790b.jpeg)

**Comment by AustinShalit** [comment] 2021-07-22 05:16
Cannot reproduce now that #46 is merged.

**Closed as completed by AustinShalit** 2021-07-22 05:16 UTC
